
spring:
  application.name: hystrix-terbine-server
server:
  port: 8765

security:
  user:
    name: admin
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/


turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-client
  clusterNameExpression: new String("default")
