
security:
  user:
    name: admin
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: config-server


